version: "3"

services:
  device-monitoring:
    image: artemprojects/device-monitoring
    volumes:
      - "./devices:/usr/src/app/resources/devices"
    restart: always
    ports:
      - 0.0.0.0:8080:8080
    environment:
      - DEMO_MODE=disable
      - MOCK_DATA_COUNT=10
      - DISCOVERY_WORKER_POOL=20
      - LOG_MODE=dev
      - TZ=Asia/Almaty
      - DISCOVERY_PERIOD_SEC=2
      - EXECUTOR_SERVICE_IMPL=PingExecutorService
